### PR TITLE
Support alternate klipper venv paths

### PR DESCRIPTION
**Pull request by kageurufu**
## Summary by Sourcery

Support alternate Klipper virtual environment paths by allowing the path to be set via the KLIPPER_VENV environment variable.

Enhancements:
- Allow customization of the Klipper virtual environment path by introducing an environment variable KLIPPER_VENV.

### CODE REVIEW

**Comment by kageurufu** [comment]
ok that sourcery thing is black magic
i need to use it on my projects 🤣

**Comment by Frix-x** [comment]
That's a good idea!

**Comment by kageurufu** [comment]
I need to do something to fix the moonraker.conf when installed this way,
perhaps embed a template in the install.sh and populate it then?
How attached are you to having the moonraker.conf separate?

**Comment by Frix-x** [comment]
Sure you can do this. I found it was easy to have it separated to just `cat moonraker.conf > target.confg`, but if you want to fill a template with custom values, you can embed it in the install.sh without any problem.

**Comment by kageurufu** [comment]
Done! Lemme know what you think

**Review by Frix-x — APPROVED** [review]
I'll merge it :)

**Pull request merged**
