### PR TITLE
added Autohoming if needed to dummy_macros.cfg

### PR DESCRIPTION
**Pull request by Zarrsito**
Some simple lines for Autohoming

## Summary by Sourcery

Enhancements:
- Add conditional autohoming to ensure the printer toolhead is homed before executing specific macros.

### CODE REVIEW

**Comment by Frix-x** [comment]
Hello thanks for this PR.
Actually this was removed on purpose to avoid crash in case the ADXL need to be mounted on the nozzle **after** homing as it's the case of all machines with a virtual inductive probe that also use a nozzle ADXL (Prusa and Ender3 for example).

But that's exactly the purpose of the `show_macros_in_webui` config variable: you can put it to `False` and then create your own macros in your config to encapsulate the call to the underscore system S&T commands as you want to :)

**Comment by Zarrsito** [comment]
oh i didnt thought about this :D but unfortunaly, how do i have to setup the macros ? simply copy from the dummy into printer.cfg and setting to false didnt work, klipper complains about the macro already existing :)

**Comment by Frix-x** [comment]
Oh yeah, just adding the `rename_existing: XXXX` should do the trick!

Shake&Tune commands are like "system" commands and you need to rename them using the provided mechanism :)

**Comment by Zarrsito** [comment]
ah, now i got it thx alot xD

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
