### PR TITLE
Variables

### PR DESCRIPTION
**Pull request by Zeanon**
Here is my initial draft for the variables file
Feel free to let me know everything you would improve :)

### CODE REVIEW

**Comment by Zeanon** [comment]
@Frix-x Any words on this?

**Comment by Frix-x** [comment]
> @Frix-x Any words on this?

Sorry I'm a bit buse with my daytime work at the moment and has no time to review it properly. I think it's already pretty good but I just want to change it a little bit to simplify the integration and make it more transparent. I'll merge it soon :)

But thanks for the PR, it's a very good base for me to work on it :)

**Comment by Zeanon** [comment]
> The variables version check i would do on a delayed gcode when starting up or at least in a dedicated function so you don't need to edit all files when there is a new version. i don't recommend using different variables versioning per ShareAndTune function.

That's a good point and actually how I do it on my plugins, I just forgot it here :)

**Comment by Frix-x** [comment]
I'll close this PR as it was implemented in the new version I'm working on as a proper Klipper plugin.

So basically it will be available like this:
```
[shaketune]
result_folder: ~/printer_data/config/K-ShakeTune_results
number_of_results_to_keep: 3
keep_raw_csv: False
```

As for the accelerometer chip, it will now be detected automatically using what is set in the [resonance_tester] section according to the axis to be measured. If you want to force a chip, you can still do so in the macro call.

**Pull request closed without merging**
