### PR TITLE
v5.0.0

### PR DESCRIPTION
**Pull request by Frix-x**
Shake&Tune v5.0.0 is a big release with many changes to the internal code, adding a dedicated `.stdata` format, a new sweep test (compatibility with the latest Klipper release). It also includes various improvements to mitigate "timer too close" errors on lower-end hardware, and a refactoring of the graph generation code for future extensibility, etc.

# Changes

* Measurements are now stored in a new custom `.stdata` format, giving more control over what is saved to disk and how it is saved. This is easily extensible to store more things in the future. This new approach to data handling also reduces the chance of "timer too close" errors, reducing problems on less powerful hosts (e.g. CB1). But it's still not perfect, so if you still encounter problems, try stopping Crowsnest, Neopixels, etc. before running a test...

* Fixes the bug introduced with the latest Klipper version (#172). Now Shake&Tune is compatible with the new sweep test, allowing pulse-only (original test) with or without additional motion sweeps to get better graphs, especially on less rigid machines. Please refer to the relevant part of the documentation to choose which test to use and when. In the same vein, the graph headers have also been updated to show what type of test was used and the associated parameters.

* Introduced a proper command line interface (CLI) for generating graphs from stored data, with support for the new compressed `.stdata` file format, but also compatible with traditional `.csv` files. This is super useful for me to debug new features offline, but you can also use it to manually (re)generate some graphs from the CSV you saved.

* The plotting code has been completely rewritten and refactored. The plotting functions are now separated from the data calculations, making it easier to add new tests or switch to a different plotting backend in the future (and yes, I do have plans for that... Stay tuned!).

* I've also added some draft code for a future Acceleration vs. Vibration vs. Smoothing trade-off plot. But the current plotting backend doesn't allow all the things I want to make it easy to read, so the code is there but disabled in this release until I find a proper way to present the data.

* Added compatibility with the "limited" kinematics of Danger-Klipper / Kalico.

* An optional `MAX_SCALE=` parameter has been added to the macros to force the energy scale on the belts and input shaper graphs to certain values. This makes it easier to compare several consecutive runs by viewing the graphs side by side with the same scale.

# Miscellaneous fixes

* Improve the startup logic to fail fast during Klipper initialization if a configuration problem is detected. This did not work properly in the past and led to problems where e.g. the `[resonance_tester]` section was missing but remained undetected and led to a crash when running a test.

* Updated CI smoke tests to run against better Klipper mockups using a fake board and kinematics instead of the previously used `kinematics: none` and also by trying against multiple Python and Klipper versions.

* Fixed incorrect marker colors in the cross-belt plots (purple/orange points were inverted on this plot).

* Increased the default timeout to 10 minutes, as the vibrations graph can take a long time to run, and some people were experiencing frequent failures due to this.

* Since the `.stdata` file format is added, I now have full control over how and when the files are written to disk. So now Shake&Tune will also wait for the file writing to be finished before starting a new accelerometer measurement. This helps with timer too close errors, but also fixes a rare bug where the vibrations graph would not completely record all the data for one of the motors.

* Added support for alternative Klippy venv in case you don't have a standard installation

### CODE REVIEW

**Review by akilgore8484 — APPROVED** [review]
Everything looks good

**Review by jpapiez — APPROVED** [review]
Updated readmes look good.

**Review by HeavilyModdedEnder3 — APPROVED** [review]
Looking good

**Comment by Frix-x** [comment]
Ok, now I think I'm ready to merge v5.0.0 with the couple of additions from tonight (new MAX_SCALE parameter and more infos in the header about the current test mode). Can you all confirm that it's still good for you?

**Comment by roykrikke** [comment]
Will you also include this in the release? https://github.com/Frix-x/klippain-shaketune/issues/140

**Comment by akilgore8484** [comment]
Looks good.  Like the additional info in the header.  Very helpful.  I have the Dev branch running on three different machines with no issues on two of them.  On the third machine I've switched back to traditional "no sweep" behavior because the sweep speed of 60mm/s just happens to be where my motors resonate the most.  I know mine is an edge case, but would be nice to be able to adjust the sweep speed.  It has a sharp resonate peak between 57 and 73 mm/s.

**Comment by Frix-x** [comment]
> Will you also include this in the release? #140

That's a Klippain config issue, but I will switch to it after v5.0.0 of S&T is released and this will likely be part of it

> I know mine is an edge case, but would be nice to be able to adjust the sweep speed

This can already be done by tweaking the `sweeping_period` of the `[resonance_tester]` config entry. If you decrease the period, I think it will go faster.
In Shake&Tune, I usually try to avoid duplicating config entries and use the ones that are in the stock Klipper if available to avoid confusion. But I may try to find a way to force it using a macro parameter and calculate the new period to display it on the graph, but if not set, default to the original sweeping_period entry. But I need to think about it a bit more to try to find the best and simplest way to do this and it will probably be for a v5.1.0 release.

**Pull request merged**
